[package]
name = "c2ded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtshark = "2.7.1"
rustls = "0.21.9"
tokio = { version = "1.34.0", features = ["full"] }
